# Generated by Django 3.0.8 on 2020-07-07 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=15)),
                ('birth_date', models.DateField(verbose_name='%Y-%m-%d')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weigth', models.IntegerField()),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
