# Generated by Django 3.0.8 on 2020-07-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_auto_20200713_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_data',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
