# Generated by Django 3.0.8 on 2020-07-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0007_auto_20200716_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_data',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('NI', 'NI')], default=None, max_length=3),
        ),
    ]
