# Generated by Django 3.0.8 on 2020-07-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0008_personal_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_data',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('NI', 'NI')], max_length=3),
        ),
    ]
