# Generated by Django 3.0.8 on 2020-07-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0009_auto_20200722_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_data',
            old_name='weigth',
            new_name='weight',
        ),
    ]
